### ISSUE TITLE
The check all boxes button makes me sad.

### ISSUE THREAD

**Issue by wraithan** [TheoChevalier/FoxShop#55]
It is located in about the same spot as the unlock button, so if FoxShop is open and I happen to hit the unlock button more than once, it hits the check all boxes button.

Also I've hit it accidentally a few times and honestly I think it should have a prompt something.

**Comment by TheoChevalier** [comment]
Good catch :)
Rather than a prompt, I propose to move it on the "More actions" screen, and even add a "Uncheck all boxes" option.
What do you think?

**Comment by wraithan** [comment]
Anywhere not on the main screen gets a :+1 from me.

**Comment by TheoChevalier** [comment]
OK, great :) I will probably fix that tomorrow
